name: CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3 

    - name: Set up CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make

    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ctest -V
